name: Image-Set-Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Image-Set-Update:
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: date
        run: echo "date=$(date +'%B %d, %Y %I:%M %p')" >> $GITHUB_OUTPUT

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.x"

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Image Set Update
        env:
          TMDBAPI: ${{ secrets.TMDBAPI }}
          TRAKT_ID: ${{ secrets.TRAKT_ID }}
          TRAKT_TOKEN: ${{ secrets.TRAKT_TOKEN }}
        run: python set_update.py

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update at ${{ steps.date.outputs.date }} UTC" -a

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}